### PR TITLE
Update docpad and dependencies

### PR DESCRIPTION
**Pull request by mkautzmann**
Hello everyone.

This PR is related to #279.

The idea is to update docpad and other dependencies so that they work with stable versions of `node` such as `v4`.

Off topic: Also found some files using CRLF while the rest of the project uses LF so changed that.

**Notice:** The assets folder was moved because docpad just copies the contents and this way it makes more sense. I've changed the `docpad.coffee` to address the changes.

**Warning:** When publishing the site notice the new location of the assets folder, the `docpad.coffee` file already points to `http://zenorocha.github.io/browser-diet/assets`

Please review the PR and let me know if I need to change anything.

Thanks!

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Works perfectly! Thanks @mkautzmann ;)

**Comment by zenorocha** [comment]
@mkautzmann https://github.com/webcomponents/webcomponents.github.io and https://github.com/braziljs/braziljs.org also need this kind of update. Let me know if you're interested, many people have trouble in contributing because of that :(

**Comment by mkautzmann** [comment]
@zenorocha Sure, I'll take a look on those as well. I will send PRs to the respective repos when ready.

**Pull request merged**
