### PR TITLE
Fixed main menu

### PR DESCRIPTION
**Pull request by pedropolisenso**
Hey @zenorocha, the proposal of fixed main menu, it is done. Issue #261

### CODE REVIEW

**Comment by pedropolisenso** [comment]
check out: http://pedropolisenso.github.io/browser-diet/en/

**Comment by pedropolisenso** [comment]
correction the title PR: Fixed main menu*

**Comment by zenorocha** [comment]
Hey Pedro,

Thanks for the pull request! Here are couple changes that needs to be done:

1) There's a redirect to your fork that needs to be removed;
2) CSS additions should be made to actual source files instead of the minified one (`all.min.css`);
3) By doing calculations on every scroll event you affect a lot of performance. Consider applying a throttle pattern (see @almirfilho's [talk for more info](https://speakerdeck.com/almirfilho/throttle-and-debounce-patterns-in-web-apps));

**Comment by pedropolisenso** [comment]
Ok @zenorocha no problems, i will make the correction :+1:

**Comment by pedropolisenso** [comment]
Hi @zenorocha i saw the talk the Almir Filho, very good the patterns. Want know if have an suggestion more nice and if can you help me?

**Comment by pedropolisenso** [comment]
i Have an solution, i'll the test and send

**Comment by pedropolisenso** [comment]
Hi @zenorocha, as did changes in the master branch that you asked, but when I try to view the status in git, returns nothing to me, you know why?

**Comment by zenorocha** [comment]
I don't know how your git commits are organized. What I suggest is to create a new branch based in master (`git checkout master && git checkout -b fixed-menu`) then submit your PR to the original master branch from there.

**Comment by pedropolisenso** [comment]
Ok @zenorocha, perfect!

**Comment by zenorocha** [comment]
Any news on this?

**Comment by pedropolisenso** [comment]
Yes @zenorocha I'm doing some tests!

**Comment by pedropolisenso** [comment]
@zenorocha New Pull Request #266

**Pull request closed without merging**
